package org.hejnaluk.hibernatetest.hibernatetest.lessons;

import org.hejnaluk.hibernatetest.hibernatetest.domain.Book;
import org.hejnaluk.hibernatetest.hibernatetest.domain.Genre;
import org.hejnaluk.hibernatetest.hibernatetest.repository.BookRepository;
import org.hejnaluk.hibernatetest.hibernatetest.repository.BookSummary;
import org.hejnaluk.hibernatetest.hibernatetest.web.BookDto;
import org.hibernate.Hibernate;
import org.hibernate.LazyInitializationException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Lazy loading, proxies, the N+1 problem and the ways to avoid it.
 */
class Lesson02FetchingTest extends HibernateLesson {

    @Autowired
    BookRepository bookRepository;

    @BeforeEach
    void startWithEmptyPersistenceContext() {
        flushAndClear();
    }

    @Test
    void nPlusOneQueries() {
        step("1 query for the books...");
        List<Book> books = bookRepository.findAll();

        step("...then 1 query per distinct publisher and 1 per book's authors collection");
        List<BookDto> dtos = books.stream().map(BookDto::from).toList();

        log.info("Loaded {} books with {} statements", dtos.size(), statements());
        // 1 (books) + 2 (publishers 1 and 3; book 7 has none) + 8 (authors of each book)
        assertThat(statements()).isEqualTo(11);
    }

    @Test
    void fetchJoinLoadsEverythingInOneQuery() {
        List<BookDto> dtos = bookRepository.findAllWithPublisherAndAuthors().stream()
                .map(BookDto::from).toList();

        assertThat(dtos).hasSize(8); // Hibernate 6+ removes the duplicate rows from the join itself
        assertThat(statements()).isEqualTo(1);
    }

    @Test
    void entityGraphLoadsEverythingInOneQuery() {
        List<BookDto> dtos = bookRepository.findByGenreOrderByTitle(Genre.TECHNICAL).stream()
                .map(BookDto::from).toList();

        assertThat(dtos).hasSize(5);
        assertThat(statements()).isEqualTo(1);
    }

    @Test
    void dtoProjectionLoadsNoEntitiesAtAll() {
        List<BookSummary> summaries = bookRepository.findSummaries();

        assertThat(summaries).hasSize(8);
        assertThat(statements()).isEqualTo(1);
        assertThat(stats.getEntityLoadCount()).isZero(); // nothing to dirty-check
        summaries.forEach(s -> log.info("{}", s));
    }

    @Test
    void lazyManyToOneIsAProxy() {
        Book book = em.find(Book.class, 4L);

        // The publisher is an uninitialized proxy: a subclass generated by Hibernate
        // that only knows its id.
        assertThat(Hibernate.isInitialized(book.getPublisher())).isFalse();
        log.info("Publisher class: {}", book.getPublisher().getClass().getName());

        step("reading the id does not need a query: the proxy already has it");
        assertThat(book.getPublisher().getId()).isEqualTo(3L);
        assertThat(statements()).isEqualTo(1);

        step("reading any other property initializes the proxy");
        assertThat(book.getPublisher().getName()).isEqualTo("Addison-Wesley");
        assertThat(statements()).isEqualTo(2);
    }

    @Test
    void getReferenceDoesNotQueryUntilYouUseIt() {
        Book reference = em.getReference(Book.class, 1L);
        assertThat(statements()).isZero();

        reference.getTitle();
        assertThat(statements()).isEqualTo(1);
    }

    @Test
    void lazyInitializationExceptionOnDetachedEntity() {
        Book book = em.find(Book.class, 1L);
        em.clear(); // book is now detached, like after the transaction/session ends

        assertThatThrownBy(() -> book.getAuthors().size())
                .isInstanceOf(LazyInitializationException.class);
    }
}
